# Generated by Django 4.0.4 on 2022-06-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firewalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgmt_ip', models.GenericIPAddressField()),
                ('state', models.BooleanField()),
                ('hostname', models.CharField(max_length=50)),
                ('premise_code', models.CharField(max_length=5)),
                ('software_version', models.CharField(max_length=12)),
                ('configuration_file', models.FileField(null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
