# Generated by Django 4.0.4 on 2022-06-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firewalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgmt_ip', models.GenericIPAddressField()),
                ('state', models.BooleanField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='False')),
                ('hostname', models.CharField(max_length=50)),
                ('vendor', models.CharField(choices=[('Palo Alto', 'Palo Alto'), ('Fortinet', 'Fortinet'), ('Juniper', 'Juniper'), ('Barracuda', 'Barracuda')], default='Fortinet', max_length=20)),
                ('premise_code', models.CharField(max_length=6)),
                ('software_version', models.CharField(blank=True, default='Unknown', max_length=12)),
                ('configuration_file', models.FileField(blank=True, upload_to='media')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
