# Generated by Django 4.0.4 on 2022-06-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewalls',
            name='state',
            field=models.BooleanField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')]),
        ),
    ]
