# Generated by Django 4.0.4 on 2022-06-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewalls',
            name='configuration_file',
            field=models.FileField(blank=True, default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
