# Generated by Django 4.0.4 on 2022-06-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_firewalls_configuration_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewalls',
            name='configuration_file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
