# Generated by Django 4.0.4 on 2022-06-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_firewalls_configuration_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewalls',
            name='vendor',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
