# Generated by Django 4.0.4 on 2022-06-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_firewalls_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewalls',
            name='state',
            field=models.BooleanField(),
        ),
    ]
