# Generated by Django 4.0.4 on 2022-06-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_firewalls_premise_code_alter_firewalls_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewalls',
            name='software_version',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='firewalls',
            name='state',
            field=models.BooleanField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')]),
        ),
    ]
