# Generated by Django 4.0.4 on 2022-06-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_firewalls_software_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewalls',
            name='software_version',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='firewalls',
            name='state',
            field=models.BooleanField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], null=True),
        ),
    ]
