# Generated by Django 4.0.4 on 2022-06-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_firewalls_software_version_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Firewalls',
            new_name='Firewall',
        ),
    ]
