# Generated by Django 4.0.4 on 2022-06-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_firewalls_firewall'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Firewall',
            new_name='Firewalls',
        ),
    ]
